# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'Maps' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Maps
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Gloss', '~> 1.0'
  
  use_frameworks!
end
